name: Prettier code formatter

on:
  pull_request:
    branches:
      - master
      - main
  push:
    branches:
      - master
      - main

jobs:
  check:
    # available images: https://github.com/actions/runner-images#available-images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v4
      - name: Install Prettier 💾
        run: npm install --save-dev --save-exact prettier @shopify/prettier-plugin-liquid
      - name: Prettier Check 🔎
        id: prettier
        run: npx prettier . --check || true
      - name: Prettier Format 🎨
        run: npx prettier . --write
      - name: Create diff 📝
        run: |
          git diff -- . ':(exclude)package-lock.json' ':(exclude)package.json' > diff.txt || true
          if [ -s diff.txt ]; then
            npm install -g diff2html-cli
            diff2html -i file -s side -F diff.html -- diff.txt
          fi
      - name: Upload html diff ⬆️
        id: artifact-upload
        if: hashFiles('diff.txt') != ''
        uses: actions/upload-artifact@v4
        with:
          name: HTML Diff
          path: diff.html
          retention-days: 7
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Prettier Action"
          git add -A
          git diff-index --quiet HEAD || git commit -m "Apply Prettier formatting"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
